#!/usr/bin/env node
/* Builds the bundles the pages load, from the sources in javascript/.
 *
 *   node tools/build.js            write dist/ and refresh the ?v= hashes in the HTML
 *   node tools/build.js --check    change nothing; exit 1 if dist/ or the HTML are out of date
 *   node tools/build.js --watch    rebuild whenever a source file changes (handy while editing)
 *
 * Plain Node, no packages. Why bundle at all: on a slow connection every separate file costs a round trip
 * and a stalled file blocks everything after it — one core file per page is about three times faster to
 * become usable (see tests/results/low-end-report.md). Files are only concatenated (no minifying, no
 * rewriting), so the code that runs is exactly the code in javascript/, in the order listed here.
 *
 * Not bundled, on purpose:  load-guard.js and appearance-core.js (tiny, must run first in the <head>),
 * archive-worker.js (a Web Worker has its own file; it also loads util.js and detail-parser.js).
 * It also generates /sw.js (the service worker) from tools/sw.template.js, versioned by a hash of every file it caches. */
const fs = require('fs'), path = require('path'), crypto = require('crypto'), zlib = require('zlib');

const ROOT = path.resolve(__dirname, '..');
// ORDER MATTERS: classic scripts share one global scope, so a file must come after the ones it uses.
const BUNDLES = {
  // the core of each page: everything needed to use it. Ends by marking the page ready (see main.js / advanced.js).
  'app-basic.js':    ['util', 'storage', 'themes', 'categories', 'detail-parser', 'db', 'raw-export', 'parser', 'math', 'goal-calculator', 'import-export', 'main'],
  'app-advanced.js': ['util', 'storage', 'themes', 'categories', 'detail-parser', 'db', 'raw-export', 'parser', 'math', 'advanced'],
  // nice-to-have pieces shared by both pages, loaded after the core (deferred): the colour panel, the phone menu
  // (wraps the picker the colour panel fills, so it comes after it) and the tutorials (which call the menu)
  'extras.js':       ['appearance-panel', 'nav-menu', 'tutorial', 'sw-register']
};
const PAGES = ['wt-log-analyzer.html', 'advanced.html'];
// Cached by the service worker (sw.js) for offline use. The bundles are added below with their ?v= URLs.
// archive-worker.js loads util.js and detail-parser.js itself, so those travel with it.
const SHELL = ['index.html', 'wt-log-analyzer.html', 'advanced.html', 'css/styles.css', 'assets/github-logo.png',
  'javascript/load-guard.js', 'javascript/appearance-core.js', 'javascript/archive-worker.js', 'javascript/util.js', 'javascript/detail-parser.js'];
const sha = s => crypto.createHash('sha256').update(s).digest('hex');

function bundleText(name, files, read) {
  const parts = files.map(f => `/* ===== javascript/${f}.js ===== */\n` + read(`javascript/${f}.js`).replace(/\r\n/g, '\n').replace(/\s+$/, '') + '\n');
  return `/* dist/${name} — GENERATED by tools/build.js. Do not edit it: edit javascript/*.js, then run \`node tools/build.js\`.\n * sources, in order: ${files.map(f => f + '.js').join(', ')} */\n` + parts.join(';\n');
}

// Returns { files: { relativePath: newText }, stale: [relativePaths that differ from what is on disk] }.
// `root` lets the tests build a copy of the site somewhere else.
function build({ write = true, root = ROOT } = {}) {
  const read = rel => fs.readFileSync(path.join(root, rel), 'utf8');
  const files = {};
  for (const [name, list] of Object.entries(BUNDLES)) files['dist/' + name] = bundleText(name, list, read);
  for (const page of PAGES) {
    // the bundle tags carry a content hash, so a changed bundle is a new URL (no stale copy from a cache or CDN)
    files[page] = read(page).replace(/(<script src="dist\/([\w-]+\.js))(?:\?v=[0-9a-f]+)?"/g, (m, head, file) => `${head}?v=${sha(files['dist/' + file]).slice(0, 8)}"`);
  }
  // the service worker: one cache name per VERSION, a hash of every file it caches, so any change anywhere is a new version
  const urls = [...SHELL, ...new Set(PAGES.flatMap(p => [...files[p].matchAll(/src="(dist\/[\w-]+\.js\?v=[0-9a-f]+)"/g)].map(m => m[1])))];
  // Text is hashed and compared in its LF form: a checkout with core.autocrlf (Windows) has CRLF on disk, and the
  // version must come out the same on every OS. (A no-op where files are already LF, so the output doesn't change.)
  const lf = s => s.replace(/\r\n/g, '\n');
  const bytes = url => {
    const rel = url.split('?')[0];
    if (files[rel] !== undefined) return Buffer.from(lf(files[rel]));
    const raw = fs.readFileSync(path.join(root, rel));
    return /\.(html|css|js)$/.test(rel) ? Buffer.from(lf(raw.toString('utf8'))) : raw;
  };
  const template = lf(fs.readFileSync(path.join(ROOT, 'tools/sw.template.js'), 'utf8')); // the template always comes from the real tools/ folder
  const version = sha(urls.map(u => u + ':' + sha(bytes(u))).join('\n') + sha(template)).slice(0, 10);
  files['sw.js'] = template.replace('__VERSION__', version).replace('__PRECACHE__', JSON.stringify(urls, null, 2));
  const onDisk = rel => { try { return lf(read(rel)); } catch (e) { return null; } };
  const stale = Object.keys(files).filter(rel => onDisk(rel) !== lf(files[rel]));
  if (write && stale.length) {
    fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
    stale.forEach(rel => fs.writeFileSync(path.join(root, rel), files[rel]));
  }
  return { files, stale };
}

module.exports = { build, BUNDLES, PAGES, SHELL };

if (require.main === module) {
  const arg = process.argv[2];
  const report = r => Object.entries(r.files).filter(([rel]) => rel.startsWith('dist/')).map(([rel, text]) =>
    `  ${rel.padEnd(22)} ${(text.length / 1024).toFixed(1).padStart(6)} KB   ${(zlib.gzipSync(text).length / 1024).toFixed(1).padStart(5)} KB gzip`).join('\n');
  if (arg === '--check') {
    const r = build({ write: false });
    if (r.stale.length) { console.error('Out of date (run `node tools/build.js`):\n  ' + r.stale.join('\n  ')); process.exit(1); }
    console.log('dist/ and the HTML are up to date.');
  } else if (arg === '--watch') {
    const go = () => { const r = build(); if (r.stale.length) console.log(new Date().toLocaleTimeString() + '  rebuilt: ' + r.stale.join(', ')); };
    go();
    let timer = null;
    fs.watch(path.join(ROOT, 'javascript'), () => { clearTimeout(timer); timer = setTimeout(go, 100); });
    console.log('Watching javascript/ — Ctrl+C to stop.');
  } else {
    const r = build();
    console.log(r.stale.length ? 'Rebuilt: ' + r.stale.join(', ') : 'Already up to date.');
    console.log(report(r));
  }
}
